version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - '7474:7474'
      - '7687:7687'
    environment:
      - NEO4J_AUTH=neo4j/valebonus
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins

  postgres:
    image: postgres:latest
    container_name: poc-postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=pocpostgres
      - POSTGRES_PASSWORD=poc-postgres
      - POSTGRES_DB=poc-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # app:
  #   build: .
  #   container_name: nestjs-app
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - neo4j
  #   environment:
  #     - NEO4J_URI=bolt://neo4j:7687
  #     - NEO4J_USER=neo4j
  #     - NEO4J_PASSWORD=test
  #   volumes:
  #     - .:/usr/src/app
  #   command: npm run start:dev

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
  postgres_data:
